apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ivrapp.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.service.ivrapp.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ivrapp.port }}
      targetPort: {{ .Values.service.ivrapp.targetPort }}
      nodePort: {{ .Values.service.ivrapp.nodePort }}
